#!/bin/sh
npm run pre-push

echo "🔍 Ejecutando lint rápido antes de push..."

npx next lint

if [ $? -ne 0 ]; then
  echo "❌ Lint falló, arregla los errores antes de hacer push."
  exit 1
fi

echo "✅ Lint aprobado, puedes hacer push."
